language: android
jdk: oraclejdk8
# Use the Travis Container-Based Infrastructure
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

script:
  - ./gradlew clean -PdisablePreDex